### ISSUE TITLE
x

### ISSUE THREAD

**Issue by ghost** [XITRIX/iTorrent_CSharp#3]
x

**Comment by XITRIX** [comment]
I can add it in testflight only for iTunes Connect users, because open beta versions are checked by apple reviewers and it is obvious that it will be refused

<img width="584" alt="2018-04-27 2 41 04" src="https://user-images.githubusercontent.com/9553519/39337232-7fbc5058-49c4-11e8-8482-6ed18ec8b64e.png">

**Comment by Basic-income** [comment]
@XITRIX 
but open betas should work, you disguise the torrent function (delete the name torrent). and just say it's a normal download manager, then it should work.

**Comment by XITRIX** [comment]
No, it is impossible, they hard check the contents of the app, before I tried to send an app, which could download the content, like download manager, but with build in web browser, and they refused it, because it could download the content from web.

**Comment by Basic-income** [comment]
really a web browser with download manager function was refused. That's crazy.

Because many apps in App Store supports a normally download manager e.g iCabMobile (browser + download manager), EDM browse receive (file manager + download manager)

can't we try other ideas? I find it extremely exciting when you find tricks and Apple can't find.

**Comment by XITRIX** [comment]
I could try, but it will take some time to add basic (not torrent) downloading functionality. Also now I hate that apple's reviewers, because I have created an app like "anime online cinema", with features like history and notifications on new episode coming out, but they are saying that "not enough functionality", and does not matter, that there are the same apps with much less functionality, so ... go to hell apple's reviewers ...

**Comment by Basic-income** [comment]
hope it works.
